server {
    listen 80;
    listen [::]:80;
    server_name game.twinsant.com;

    location ^~ /.well-known/acme-challenge/ {
        root /root/projects/sl;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name game.twinsant.com;

    ssl_certificate /etc/nginx/game.twinsant.com_bundle.crt;
    ssl_certificate_key /etc/nginx/game.twinsant.com.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /root/projects/sl;
    index index.html;

    add_header Cross-Origin-Opener-Policy same-origin always;
    add_header Cross-Origin-Embedder-Policy require-corp always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.wasm$ {
        default_type application/wasm;
        gzip_static on;
        try_files $uri =404;
    }

    location ~* \.pck$ {
        default_type application/octet-stream;
        try_files $uri =404;
    }
}